/**
 * Generated by the Babylon.JS Editor v4.0.0-beta.2
 */

import { Scene } from "@babylonjs/core";
import { attachScripts, configurePostProcesses } from "../tools";

/**
 * Defines the map of all available scripts in the project.
 */
const scriptsMap = {
	"src/scenes/scene/ball.ts": require("./ball.ts"),
	"src/scenes/scene/block.ts": require("./block.ts"),
	"src/scenes/scene/blockGenerator.ts": require("./blockGenerator.ts"),
	"src/scenes/scene/GameManager.ts": require("./GameManager.ts"),
	"src/scenes/scene/HUD.ts": require("./HUD.ts"),
	"src/scenes/scene/p_player.ts": require("./p_player.ts"),
	"src/scenes/scene/wall_center.ts": require("./wall_center.ts"),
	"src/scenes/scene/wall_left.ts": require("./wall_left.ts"),
	"src/scenes/scene/wall_right.ts": require("./wall_right.ts"),
}

/**
 * Works as an helper, this will:
 * = attach scripts on objects.
 * @param scene the scene to attach scripts, etc.
 */
export async function runScene(scene: Scene, rootUrl?: string): Promise<void> {
    // Attach scripts to objects in scene.
    attachScripts(scriptsMap, scene);

    // Configure post-processes
    configurePostProcesses(scene, rootUrl);
}
