/**
 * Generated by the Babylon.JS Editor v4.0.0-beta.7
 */
import { Scene } from "@babylonjs/core";
/**
 * Defines the map of all available scripts in the project.
 */
export declare const scriptsMap: {
    "src/scenes/scene/ball.ts": any;
    "src/scenes/scene/block.ts": any;
    "src/scenes/scene/game.ts": any;
    "src/scenes/scene/player.ts": any;
    "src/scenes/scene/wall.ts": any;
};
/**
 * Works as an helper, this will:
 * = attach scripts on objects.
 * @param scene the scene to attach scripts, etc.
 */
export declare function runScene(scene: Scene, rootUrl?: string): Promise<void>;
